# Generated by Django 4.2.1 on 2023-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Active', 'Active'), ('Closed', 'Closed')], default='Waiting', max_length=20),
        ),
    ]
